---
- hosts: all
  become: true
  vars:
    tf_version: 0.12.16
    eksctl_version: "latest_release"

  tasks:

  - name: update python
    apt:
      name: python3
      update_cache: yes
      state: latest

  - name: install python3-pip
    apt:
      name: python3-pip
      state: latest

  - name: install awscli
    pip:
      name: awscli
      extra_args: --upgrade
      state: present
      executable: pip3

  - name: download terraform zip
    get_url:
      url: "https://releases.hashicorp.com/terraform/{{ tf_version }}/terraform_{{ tf_version }}_linux_amd64.zip"
      dest: /tmp/

  - name: install unzip
    apt:
      name: unzip
      state: present
  
  - name: unzip terraform
    unarchive:
      remote_src: yes
      src: "/tmp/terraform_{{ tf_version }}_linux_amd64.zip"
      dest: /usr/local/bin/

  - name: get eksctl tar
    get_url:
      url: "https://github.com/weaveworks/eksctl/releases/download/{{ eksctl_version }}/eksctl_Linux_amd64.tar.gz"
      dest: /tmp/

  - name: untar eksctl
    unarchive:
      remote_src: yes
      src: /tmp/eksctl_Linux_amd64.tar.gz
      dest: /usr/local/bin/

  - name: get kubectl 1.14
    get_url:
      url: "https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl"
      dest: /usr/local/bin/
      mode: +x

  - name: Install Microk8s with option --classic
    snap:
      name: microk8s
      classic: yes

  - name: Add user to Microk8s group
    command: usermod -a -G microk8s root

  - name: Re-enter user session
    command: su - $USER

  - name: Check cluster status
    command: microk8s.status --wait-ready
      